import type { CustomEntitySpec } from '@open-mercato/shared/modules/entities'

const entities: CustomEntitySpec[] = [
  {
    id: 'cpq:cpq_product_specification',
    label: 'Product Specification',
    description: 'CPQ product blueprint — defines attributes, dependencies, and relationships.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_product_offering',
    label: 'Product Offering',
    description: 'Sellable instance of a product specification with design-time values and charges.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_product_relationship',
    label: 'Product Relationship',
    description: 'Structural relationship between product specifications (parent_child, requires, excludes).',
    labelField: 'id',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_product_attribute',
    label: 'Product Attribute',
    description: 'Configurable attribute definition for a CPQ product.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_product_charge',
    label: 'Product Charge',
    description: 'Charge definition (NRC/MRC/usage) for a CPQ product.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_pricing_table',
    label: 'Pricing Table',
    description: 'Multi-dimensional pricing table with named price columns.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_pricing_table_entry',
    label: 'Pricing Table Entry',
    description: 'Individual row in a pricing table with dimension values and prices.',
    labelField: 'id',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_price_rule',
    label: 'Price Rule',
    description: 'Post-calculation price adjustment rule (discount, surcharge, override).',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_bundle_slot',
    label: 'Bundle Slot',
    description: 'Structural slot within a bundle specification — defines what component specs can fill it.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_offering_component',
    label: 'Offering Component',
    description: 'Links a bundle offering to a specific component offering within a slot.',
    labelField: 'id',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_quote_configuration',
    label: 'Quote Configuration',
    description: 'CPQ-specific configuration data for a sales quote.',
    labelField: 'id',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_quote_line_configuration',
    label: 'Quote Line Configuration',
    description: 'CPQ-specific configuration for a sales quote line (one per offering).',
    labelField: 'id',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_wizard_definition',
    label: 'Wizard Definition',
    description: 'CPQ wizard definition — multi-step guided quoting flow.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_inventory_subscription',
    label: 'Inventory Subscription',
    description: 'Commercial wrapper grouping subscription items under shared contractual terms.',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_inventory_subscription_item',
    label: 'Inventory Subscription Item',
    description: 'Concrete product/service record within an inventory subscription.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_inventory_asset',
    label: 'Inventory Asset',
    description: 'Tangible or intangible thing the customer owns — hardware, licenses, fees.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_order_configuration',
    label: 'Order Configuration',
    description: 'CPQ-specific configuration data for a sales order.',
    labelField: 'id',
    showInSidebar: false,
    fields: [],
  },
  {
    id: 'cpq:cpq_order_line_configuration',
    label: 'Order Line Configuration',
    description: 'CPQ-specific configuration for a sales order line (one per offering).',
    labelField: 'id',
    showInSidebar: false,
    fields: [],
  },
]

export { entities }
export default entities
